// Generated by gencpp from file diffbot_msgs/Encoder.msg
// DO NOT EDIT!


#ifndef DIFFBOT_MSGS_MESSAGE_ENCODER_H
#define DIFFBOT_MSGS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace diffbot_msgs
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , encoders()  {
      encoders.assign(0);
  }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoders()  {
  (void)_alloc;
      encoders.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<int32_t, 2>  _encoders_type;
  _encoders_type encoders;





  typedef boost::shared_ptr< ::diffbot_msgs::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffbot_msgs::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::diffbot_msgs::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::diffbot_msgs::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::diffbot_msgs::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffbot_msgs::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffbot_msgs::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace diffbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'diffbot_msgs': ['/home/muhammed/Videolar/diff_robot/src/diffbot/diffbot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffbot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "608278b453add8de9702c9815f58b7b2";
  }

  static const char* value(const ::diffbot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x608278b453add8deULL;
  static const uint64_t static_value2 = 0x9702c9815f58b7b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::diffbot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffbot_msgs/Encoder";
  }

  static const char* value(const ::diffbot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffbot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold number of ticks from Encoders\n\
Header header\n\
\n\
# Use an array of size two of type int32 for the two encoders.\n\
# int32 is used instead of int64 because it is not supporte by Arduino/Teensy.\n\
# An overflow is also unlikely with the encoders of the DG01D-E \n\
# motor with encoder because of its low encoder resolution\n\
int32[2] encoders\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::diffbot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffbot_msgs::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoders);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffbot_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffbot_msgs::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoders[]" << std::endl;
    for (size_t i = 0; i < v.encoders.size(); ++i)
    {
      s << indent << "  encoders[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.encoders[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFBOT_MSGS_MESSAGE_ENCODER_H
